# Generated by Django 2.1.15 on 2022-09-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.PositiveIntegerField()),
                ('vehicle_id', models.PositiveIntegerField()),
                ('customer_id', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
            ],
        ),
    ]
