# Generated by Django 4.1.1 on 2022-09-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_trip_volume_trip_address_trip_address_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
