# Generated by Django 4.1.1 on 2022-09-08 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_delete_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.PositiveIntegerField()),
                ('vehicle_id', models.PositiveIntegerField()),
                ('customer_id', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50, null=True)),
                ('cargo_tonnage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('address_type', models.CharField(choices=[('pickup_point', 'pickup_point'), ('drop_off_point', 'drop_off_point')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('done_by_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
